# Example configuration options that can be placed in your main SiriProxy config.yml

############################################
# NOTICE: Modifying these options in this 
#         file has no effect. You must put 
#         them in SiriProxy's config.yml!
############################################

    - name: 'Channels'
      git: 'git://github.com/Number1/siriproxy-channels.git'
      host: '192.168.0.3'
      episode_prefix: 'http://tvlistings.aol.com/episodes/'
      image_prefix: 'http://media.i.tv.s3.amazonaws.com/channels/black/46x35/'		